---
- name: clone ossec-wazuh git repo
  shell: cd /opt && rm -rf ossec-wazuh && git clone https://github.com/wazuh/ossec-wazuh

- name: copy preloaded var file
  template:
    src=install-preloaded-vars.conf
    dest=/opt/ossec-wazuh/etc/preloaded-vars.conf

- name: install ossec-wazuh
  shell: cd /opt/ossec-wazuh && ./install.sh

- name: Generate self-signed cert
  command: openssl req -new -newkey rsa:4096 -days 10000 -nodes -subj "/" -x509 -keyout /var/ossec/etc/sslmanager.key -out /var/ossec/etc/sslmanager.cert

# ossec-remoted won't run unless there's a record for a client.
# We will add a record that allows connections from 127.0.0.1
- name: Add keepalive client.keys
  copy:
    src=client.keys
    dest=/var/ossec/etc
    owner=root
    group=ossec
    mode=440

- name: Copy init.d for authd
  copy:
    src=ossec-authd
    dest=/etc/init.d
    mode=0755
  register: ossec_authd_service

- name: Autostart authd
  service:
    name=ossec-authd
    state=restarted
    enabled=yes
  when: ossec_authd_service.changed

- name: Copy init.d for remoted
  copy:
    src=ossec-remoted
    dest=/etc/init.d
    mode=0755
  register: ossec_serverd_service

- name: Autostart remoted
  service:
    name=ossec-remoted
    state=restarted
    enabled=yes
  when: ossec_serverd_service.changed
 
- name: restart ossec server
  command: /var/ossec/bin/ossec-control restart
