---
- apt_key:
    # If you need to change the key use at least gpg --keyid-format long keyfile
    # the 32-bit short format is easily collided and insecure.
    url=http://ossec.wazuh.com/repos/apt/conf/ossec-key.gpg.key
    id=14B9C8DB9A1B1C65

- apt_repository:
    repo='deb http://ossec.wazuh.com/repos/apt/ubuntu/ {{ansible_distribution_release}} main'
    state=present

- apt:
    name=ossec-hids
  notify: restart ossec-server

- template:
    src=ossec.conf
    dest=/var/ossec/etc/ossec.conf
    owner=root
    group=ossec

